version: 2.1

orbs:
  macos: circleci/macos@2.4.1
  
jobs:
  build:
    macos:
      xcode: 15.0.0
    resource_class: macos.m1.medium.gen1
    
    steps:
      - run: xcodebuild -version
      - run: brew --version
      - run:
          command: |
            while true; do
              sleep 600
              echo "this in running in the background"
            done
          background: true
      - macos/enable-vnc
      
    
      
workflows:
  say-hello-workflow:
    jobs:
      - build
